<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Yearly Salary Report - {{ $salary->employee->name }} - {{ $selectedYear }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        @media print {
            .no-print { display: none; }
            body { padding: 0; }
            .page-break { page-break-after: always; }
        }
        
        body {
            background: #f5f5f5;
            padding: 20px;
        }
        
        .report-container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            padding: 30px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
        
        .company-header {
            text-align: center;
            border-bottom: 3px solid #667eea;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        
        .company-header h1 {
            color: #667eea;
            margin: 0;
        }
        
        .report-title {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 30px;
            text-align: center;
        }
        
        .salary-version-badge {
            display: inline-block;
            padding: 5px 10px;
            border-radius: 3px;
            font-size: 0.85em;
            font-weight: bold;
            background: #667eea;
            color: white;
        }
        
        .month-card {
            margin-bottom: 15px;
            border: 1px solid #dee2e6;
            border-radius: 5px;
        }
        
        .month-header {
            background: #f8f9fa;
            padding: 10px 15px;
            border-bottom: 1px solid #dee2e6;
            font-weight: bold;
        }
        
        .total-summary {
            background: #667eea;
            color: white;
            padding: 20px;
            border-radius: 5px;
            margin-top: 30px;
        }
    </style>
</head>
<body>
    <div class="report-container">
        <!-- Header -->
        <div class="company-header">
            <h1>HRMS</h1>
            <p class="mb-0">Human Resource Management System</p>
        </div>

        <!-- Report Title -->
        <div class="report-title">
            <h2 class="mb-0">
                <i class="fas fa-chart-line me-2"></i>
                Annual Salary Report {{ $selectedYear }}
            </h2>
        </div>

        <!-- Employee Information -->
        <div class="employee-info bg-light p-3 rounded mb-4">
            <div class="row">
                <div class="col-md-6">
                    <h5 class="text-primary">Employee Information</h5>
                    <p class="mb-1"><strong>Name:</strong> {{ $salary->employee->name }}</p>
                    <p class="mb-1"><strong>Email:</strong> {{ $salary->employee->email }}</p>
                    <p class="mb-1"><strong>Position:</strong> {{ $salary->employee->position->name ?? 'N/A' }}</p>
                </div>
                <div class="col-md-6">
                    <h5 class="text-primary">Report Period</h5>
                    <p class="mb-1"><strong>Year:</strong> {{ $selectedYear }}</p>
                    <p class="mb-1"><strong>Generated:</strong> {{ now()->format('F d, Y g:i A') }}</p>
                    <p class="mb-1"><strong>Generated By:</strong> {{ auth()->user()->name }}</p>
                </div>
            </div>
        </div>

        <!-- Salary History (Version Changes) -->
        @if($salaryVersions && $salaryVersions->count() > 1)
            <h4 class="mt-4 mb-3 text-primary">
                <i class="fas fa-history me-2"></i>
                Salary History for {{ $selectedYear }}
            </h4>
            <div class="alert alert-info">
                <i class="fas fa-info-circle"></i>
                This employee had {{ $salaryVersions->count() }} salary version(s) during {{ $selectedYear }}.
            </div>
            <div class="table-responsive mb-4">
                <table class="table table-bordered">
                    <thead class="table-dark">
                        <tr>
                            <th>Version</th>
                            <th>Fixed Salary</th>
                            <th>Effective From</th>
                            <th>Effective To</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($salaryVersions as $version)
                            <tr>
                                <td>
                                    <span class="salary-version-badge">V{{ $version->version }}</span>
                                </td>
                                <td><strong>${{ number_format($version->fixed_salary, 2) }}</strong></td>
                                <td>{{ $version->effective_date->format('M Y') }}</td>
                                <td>{{ $version->end_date ? $version->end_date->format('M Y') : 'Current' }}</td>
                                <td>
                                    <span class="badge bg-{{ $version->status === 'active' ? 'success' : 'secondary' }}">
                                        {{ ucfirst($version->status) }}
                                    </span>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        @endif

        <!-- Monthly Breakdown -->
        <h4 class="mt-4 mb-3 text-primary">
            <i class="fas fa-calendar-alt me-2"></i>
            Monthly Breakdown for {{ $selectedYear }}
        </h4>

        @php
            $yearTotalGross = 0;
            $yearTotalBonuses = 0;
            $yearTotalAdvances = 0;
            $yearTotalDeductions = 0;
            $yearTotalNet = 0;
            $monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
        @endphp

        <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead class="table-dark">
                    <tr>
                        <th>Month</th>
                        <th>Fixed Salary</th>
                        <th>Bonuses</th>
                        <th>Advances</th>
                        <th>Deductions</th>
                        <th>Net Salary</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(range(1, 12) as $month)
                        @if(isset($monthlyData[$month]))
                            @php
                                $data = $monthlyData[$month];
                                $yearTotalGross += $data['fixed_salary'];
                                $yearTotalBonuses += $data['bonuses_total'];
                                $yearTotalAdvances += $data['advances_total'];
                                $yearTotalDeductions += $data['deductions_total'];
                                $yearTotalNet += $data['net_salary'];
                            @endphp
                            <tr>
                                <td>
                                    <strong>{{ $monthNames[$month - 1] }}</strong>
                                    @if(isset($data['salary_version']))
                                        <span class="salary-version-badge ms-2" style="font-size: 0.7em;">V{{ $data['salary_version'] }}</span>
                                    @endif
                                </td>
                                <td>${{ number_format($data['fixed_salary'], 2) }}</td>
                                <td class="text-success">+${{ number_format($data['bonuses_total'], 2) }}</td>
                                <td class="text-danger">-${{ number_format($data['advances_total'], 2) }}</td>
                                <td class="text-danger">-${{ number_format($data['deductions_total'], 2) }}</td>
                                <td><strong>${{ number_format($data['net_salary'], 2) }}</strong></td>
                            </tr>
                        @else
                            <tr class="table-secondary">
                                <td>{{ $monthNames[$month - 1] }}</td>
                                <td colspan="5" class="text-center text-muted">No salary data</td>
                            </tr>
                        @endif
                    @endforeach
                </tbody>
                <tfoot class="table-primary">
                    <tr>
                        <th>YEAR TOTAL</th>
                        <th>${{ number_format($yearTotalGross, 2) }}</th>
                        <th class="text-success">+${{ number_format($yearTotalBonuses, 2) }}</th>
                        <th class="text-danger">-${{ number_format($yearTotalAdvances, 2) }}</th>
                        <th class="text-danger">-${{ number_format($yearTotalDeductions, 2) }}</th>
                        <th><strong>${{ number_format($yearTotalNet, 2) }}</strong></th>
                    </tr>
                </tfoot>
            </table>
        </div>

        <!-- Summary Statistics -->
        <div class="total-summary">
            <h4 class="text-center mb-4">Annual Summary {{ $selectedYear }}</h4>
            <div class="row text-center">
                <div class="col-md-3">
                    <h5 class="mb-0">${{ number_format($yearTotalGross, 2) }}</h5>
                    <small>Total Gross</small>
                </div>
                <div class="col-md-3">
                    <h5 class="mb-0">${{ number_format($yearTotalBonuses, 2) }}</h5>
                    <small>Total Bonuses</small>
                </div>
                <div class="col-md-3">
                    <h5 class="mb-0">${{ number_format($yearTotalAdvances + $yearTotalDeductions, 2) }}</h5>
                    <small>Total Deductions</small>
                </div>
                <div class="col-md-3">
                    <h5 class="mb-0 fs-3">${{ number_format($yearTotalNet, 2) }}</h5>
                    <small>Total Net Pay</small>
                </div>
            </div>
        </div>

        <!-- Footer -->
        <div class="mt-5 pt-3 border-top">
            <div class="row">
                <div class="col-6">
                    <p class="text-muted small">This is a computer-generated document. No signature is required.</p>
                </div>
                <div class="col-6 text-end">
                    <p class="mb-5">_______________________</p>
                    <p><strong>HR Manager Signature</strong></p>
                </div>
            </div>
        </div>

        <!-- Action Buttons -->
        <div class="text-center mt-4 no-print">
            <button onclick="window.print()" class="btn btn-primary me-2">
                <i class="fas fa-print"></i> Print Report
            </button>
            <button onclick="window.close()" class="btn btn-secondary">
                <i class="fas fa-times"></i> Close
            </button>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

